[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
clap = { version = "4.5.21", features = ["derive", "cargo"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
core = { path = "../core" }
